# Note  : *** the batch_size should be equal to the gpus number at the test phase!!! ***
data_cfg:
  dataset_name: OUMVLP
  dataset_root: ./data_oumvlp/
  dataset_partition: ./misc/partitions/OUMVLP.json
  num_workers: 0
  remove_no_gallery: false
  test_dataset_name: OUMVLP
  cache: true

evaluator_cfg:
  enable_distributed: true
  enable_float16: false 
  restore_ckpt_strict: true
  restore_hint: 0
  save_name: GaitGL_view_mo_em64_32
  sampler:
    batch_size: 4
    sample_type: all_ordered
    type: InferenceSampler

loss_cfg:
  - loss_term_weights: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weights: 1.0
    scale: 1
    type: CrossEntropyLoss
    log_accuracy: true
    label_smooth: true
    log_prefix: softmax
  - loss_term_weights: 0.2
    scale: 1
    type: CrossEntropyLoss
    log_accuracy: true
    label_smooth: false
    log_prefix: view_softmax

model_cfg:
  model: GaitGL_view
  channels: [32, 64, 128, 256]
  class_num: 5153
  view_num: 14

optimizer_cfg:
  lr: 1.0e-4
  solver: Adam
  weight_decay: 0

scheduler_cfg:
  gamma: 0.1
  milestones:
    - 340000
    - 380000
  scheduler: MultiStepLR

trainer_cfg:
  enable_distributed: true
  enable_float16: False
  with_test: false
  log_iter: 100
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 20000
  save_name: GaitGL_view_mo_em64_32
  sync_BN: true
  total_iter: 440000
  sampler:
    batch_shuffle: true
    batch_size:
      - 16
      - 8
    frames_num_fixed: 30
    frames_skip_num: 0
    sample_type: fixed_ordered
    type: TripletSampler
  with_test: True